SET SERVEROUTPUT ON
DECLARE
	CURSOR EMP_CUR IS
	SELECT  last_name,salary,hire_date FROM EMPLOYEES;
    	ENAME VARCHAR2(25);
	SAL   NUMBER(7,2);
	HIREDATE DATE;
BEGIN
	OPEN EMP_CUR;
	FETCH EMP_CUR INTO ENAME,SAL,HIREDATE;
	WHILE EMP_CUR%FOUND
	LOOP
	IF SAL > 15000 AND HIREDATE >=  TO_DATE('01-FEB-1988','DD-MON-YYYY') THEN
	DBMS_OUTPUT.PUT_LINE (ENAME ||  ' earns ' || TO_CHAR(SAL)||  ' and joined the organization on ' || TO_DATE(HIREDATE,'DD-Mon-YYYY'));
	 	END IF;
                FETCH EMP_CUR INTO ENAME,SAL,HIREDATE;
	END LOOP;
CLOSE EMP_CUR;
END;
/
SET SERVEROUTPUT OFF

 