DECLARE
	DUE_FOR_RAISE EXCEPTION;
	HIREDATE EMPLOYEES.HIRE_DATE%TYPE;
	ENAME EMPLOYEES.LAST_NAME%TYPE :=  INITCAP( '& P_ENAME');
	SAL EMPLOYEES.SALARY%TYPE;
	YEARS NUMBER(2);
BEGIN
	SELECT LAST_NAME,SALARY,HIRE_DATE 
	INTO  ENAME,SAL,HIREDATE
	FROM employees WHERE last_name =  ENAME;
	YEARS := MONTHS_BETWEEN(SYSDATE,HIREDATE)/12;
	IF SAL < 3500 AND YEARS > 5  THEN
		RAISE DUE_FOR_RAISE;
	ELSE
		DBMS_OUTPUT.PUT_LINE ('Not due for a raise');
	END IF;
	
EXCEPTION
	WHEN DUE_FOR_RAISE THEN
	INSERT INTO ANALYSIS(ENAME,YEARS,SAL)
	VALUES (ENAME,YEARS,SAL);
END;
/
  

	 