DECLARE
	SAL NUMBER(7,2);
	LASTNAME EMPLOYEES.LAST_NAME%TYPE;
	
BEGIN
	SELECT salary INTO SAL
	FROM employees WHERE last_name = INITCAP('&P_LASTNAME')
         FOR UPDATE of salary;
	LASTNAME := INITCAP('&P_LASTNAME');
	IF SAL < 3000 THEN
		UPDATE employees SET salary = salary + 500
		WHERE last_name =  INITCAP('&P_LASTNAME') ;
		DBMS_OUTPUT.PUT_LINE (LASTNAME || '''s salary updated');
	ELSE
		DBMS_OUTPUT.PUT_LINE (LASTNAME  || ' earns ' || TO_CHAR(SAL));
	END IF;
END;
/ 
SET SERVEROUTPUT OFF
UNDEFINE P_LASTNAME