SET SERVEROUTPUT ON
DEFINE P_SALARY = 5000
DECLARE
	SAL  NUMBER(7,2) := &P_SALARY;
	BONUS   NUMBER(7,2);
	ANN_SALARY NUMBER(15,2);
BEGIN
	ANN_SALARY := SAL * 12;
	IF ANN_SALARY >= 20000 THEN
		BONUS := 2000;
	ELSIF ANN_SALARY <= 19999 AND ANN_SALARY >=10000 THEN
		BONUS := 1000;
	ELSE
		BONUS := 500;
	END IF;
	DBMS_OUTPUT.PUT_LINE ('The Bonus is $  ' || TO_CHAR(BONUS));
END;
/
SET SERVEROUTPUT OFF	