SET SERVEROUTPUT ON
DECLARE
	MESSAGE VARCHAR2(35);
	DATE_WRITTEN DATE;
       BEGIN
	MESSAGE := 'This is my first PLSQL Program';
	DATE_WRITTEN := SYSDATE;
	INSERT INTO temp(CHAR_STORE,DATE_STORE)
	VALUES (MESSAGE,DATE_WRITTEN);
END;
/
SELECT * FROM TEMP;